include:
  - ./docker-compose.ch-dev.yaml

services:

  postgres-admin:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=theatre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data_admin:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-auth:
    build: docker/pg-auth
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/pg-auth/init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
      - pg_data_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=auth

  jaeger-init:
    image: busybox
    entrypoint: ["/bin/sh", "/scripts/init_jaeger_badger.sh"]
    volumes:
      - jaeger_data:/badger
      - ./scripts/init_jaeger_badger.sh:/scripts/init_jaeger_badger.sh:ro

  jaeger-tracer:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4317:4317
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    depends_on:
      jaeger-init:
        condition: service_completed_successfully
    volumes:
      - jaeger_data:/badger

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    restart: unless-stopped

  admin-panel:
    build: ./admin_panel
    ports:
      - "8000:8000"
    volumes:
      - static_value:/admin_panel/app/static/
      - ./auth-certs/jwt-public.pem:/run/secrets/jwt/jwt-public.pem:ro
    env_file:
      - env-files/.env.admin
    depends_on:
      postgres-admin:
        condition: service_healthy

  admin-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./admin_panel/openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    depends_on:
      - admin-panel

  architecture-renderer:
    image: plantuml/plantuml:latest
    entrypoint: ["/bin/sh", "/scripts/render_project_schemas.sh"]
    volumes:
      - ./architecture-raw:/input:ro
      - ./architecture-rendered:/output
      - ./scripts/render_project_schemas.sh:/scripts/render_project_schemas.sh:ro

  elastic-db:
    image: elasticsearch:8.6.2
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  elastic-init:
    image: curlimages/curl:latest
    depends_on:
      elastic-db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/scripts/create_elastic_indexes.sh"]
    volumes:
      - ./elasticsearch/indexes:/data/indexes:ro
      - ./scripts/create_elastic_indexes.sh:/scripts/create_elastic_indexes.sh:ro
    restart: on-failure

  movies-etl:
    build: ./movies_etl
    volumes:
      - etl_state:/opt/app/data
    env_file:
      - env-files/.env.etl
    depends_on:
      postgres-admin:
        condition: service_healthy
      elastic-init:
        condition: service_completed_successfully
    restart: unless-stopped


  movies-api:
    build: movies_api/
    ports:
      - "8001:8000"
    env_file:
      - env-files/.env.movies
    depends_on:
      elastic-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./auth-certs/jwt-public.pem:/run/secrets/jwt/jwt-public.pem:ro
    restart: unless-stopped

  auth-api:
    build: auth_api/
    ports:
      - "8002:8000"
    env_file:
      - env-files/.env.auth
    depends_on:
      postgres-auth:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger-tracer:
        condition: service_started
    volumes:
      - ./auth-certs:/run/secrets/jwt:ro

  ugc-api:
    build: ugc_api/
    ports:
      - "8003:8000"
    env_file:
      - env-files/.env.ugc-api
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    volumes:
      - ./auth-certs/jwt-public.pem:/run/secrets/jwt/jwt-public.pem:ro
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # KRaft
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # Broker settings
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=6
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka-init:
    image: apache/kafka:4.1.0
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_CONFIGS: ugc-events,3,1;ugc-anonymous-events,3,1
    volumes:
      - ./scripts/init_kafka_ugc.sh:/scripts/init_kafka_ugc.sh:ro
    entrypoint:
      - /bin/bash
      - /scripts/init_kafka_ugc.sh

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka-init:
        condition: service_completed_successfully

volumes:
  pg_data_admin:
  pg_data_auth:
  static_value:
  es_data:
  etl_state:
  jaeger_data:
  kafka_data:
