services:

  postgres-admin:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${ADMIN_POSTGRES_DB}
      - POSTGRES_USER=${ADMIN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ADMIN_POSTGRES_PASSWORD}
    volumes:
      - pg_data_admin:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ADMIN_POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  admin-panel:
    build: ./admin_panel
    volumes:
      - static_value:/admin_panel/app/static/
    env_file:
      - admin_panel/.env
    environment:
      - POSTGRES_DB=${ADMIN_POSTGRES_DB}
      - POSTGRES_USER=${ADMIN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ADMIN_POSTGRES_PASSWORD}
    depends_on:
      postgres-admin:
        condition: service_healthy

  admin-swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./admin_panel/openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    depends_on:
      - admin-panel
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_value:/var/www/static/
    depends_on:
      postgres-admin:
        condition: service_healthy

  elastic-db:
    image: elasticsearch:8.6.2
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  elastic-init:
    image: curlimages/curl:latest
    depends_on:
      elastic-db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/scripts/create_elastic_indexes.sh"]
    volumes:
      - ./elasticsearch/indexes:/data/indexes:ro
      - ./scripts/create_elastic_indexes.sh:/scripts/create_elastic_indexes.sh:ro
    restart: on-failure

  movies-etl:
    build: movies_etl
    volumes:
      - etl_state:/opt/app/data
    env_file:
      - movies_etl/.env
    environment:
      - STATE_FILE_PATH=/etl_state/state.json
    depends_on:
      postgres-admin:
        condition: service_healthy
      elastic-init:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  pg_data_admin:
  static_value:
  es_data:
  etl_state:
