server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;
    server_tokens off;
    
    root /data;

    location ~* \.(?:jpg|jpeg|gif|png|ico|css|js)$ {
        log_not_found off;
        expires 90d;
    }

    location ^~ /admin/docs/ {
        proxy_pass http://admin-swagger:8080/;
    }

    location ^~ /admin/api/ {
        proxy_pass http://admin-panel:8000/api/;
    }

    location /admin/ {
        proxy_pass http://admin-panel:8000;
    }

    location ^~ /static/ {
        alias /var/www/static/;
    }

    location /movies/api/ {
        limit_req zone=one burst=5;
        proxy_pass http://movies-api:8000/;
    }

    location /auth/api/ {
        proxy_pass http://auth-api:8000/;
    }

    location ^~ /tracer/ {
        proxy_pass http://jaeger-tracer:16686/tracer/;
    }

    location /architecture/ {
        alias /var/www/schema-render/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }
}
