filebeat.inputs:
  - type: filestream
    id: auth-api
    enabled: true
    paths:
      - /var/log/auth-api/app*.json*
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
    fields:
      service:
        name: auth-api
    fields_under_root: true

  - type: filestream
    id: movies-api
    enabled: true
    paths:
      - /var/log/movies-api/app*.json*
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
    fields:
      service:
        name: movies-api
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5045"]