input {
  beats {
    port => 5045
    host => "0.0.0.0"
  }
}

output {
  if [service][name] == "auth-api" {
    elasticsearch {
      hosts => [ "${ES_HOST}" ]
      index => "auth-api-%{+yyyy.MM.dd}"
      ilm_enabled => false
      manage_template => false
    }
  } else if [service][name] == "movies-api" {
    elasticsearch {
      hosts => [ "${ES_HOST}" ]
      index => "movies-api-%{+yyyy.MM.dd}"
      ilm_enabled => false
      manage_template => false
    }
  } else {
    stdout { codec => rubydebug }
  }
}