input {
    beats {
        port => 5045
        host => "0.0.0.0"
        codec => "json"
      }
}
filter {
}
output {
  if "nginx" in [tag] or "nginx" in [tags]  {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "nginx-%{+YYYY.MM.dd}"
      }
  }
  else if "auth_app" in [tag] or "auth_app" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "auth_app-%{+YYYY.MM.dd}"
      }
  }
  else if "content_etl" in [tag] or "content_etl" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "content_etl-%{+YYYY.MM.dd}"
      }
  }
  else if "content_app" in [tag] or "content_app" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "content_app-%{+YYYY.MM.dd}"
      }
  }
  else if "admin_app" in [tag] or "admin_app" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "admin_app-%{+YYYY.MM.dd}"
      }
  }
  else if "ugc_app" in [tag] or "ugc_app" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "ugc_app-%{+YYYY.MM.dd}"
      }
  }
  else if "ugc_etl" in [tag] or "ugc_etl" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "ugc_etl-%{+YYYY.MM.dd}"
      }
  }
  else if "ugc_api" in [tag] or "ugc_api" in [tags] {
    elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "ugc_api-%{+YYYY.MM.dd}"
      }
  }
  else if "websocker_server" in [tag] or "websocker_server" in [tags] {
    elasticsearch {
      hosts => [ "${ES_HOST}" ]
      index => "websocker_server-%{+YYYY.MM.dd}"
    }
  }
  else if "email_worker" in [tag] or "email_worker" in [tags] {
    elasticsearch {
      hosts => [ "${ES_HOST}" ]
      index => "email_worker-%{+YYYY.MM.dd}"
    }
  }
  stdout {}
}